
# Outdoor sporting event
## Post-event survey

The data you have access to is the feedback collected from the 2019 post-event survey.

### Business problem
We are interested in gaining insights from the 2019 feedback in order to help us plan for future events. In particular, we are interested in any (or all) of the following:

* Transport planning and parking is a main factor in event organisation. As our events are held in areas of natural interest, we try to limit single-car occupancy and parking to necessary areas. It would be useful to know how people travelled to the 2019 event, and if possible use the data to predict travel patterns for future events.   

* It would also be interesting to know where people travelled from, where most people stayed during the event, and how far away from the event region people were willing to stay. Is there a specific radius of the event within which people preferred to remain? Did participants prefer a certain type of accommodation? All of this information will help us decide where to hold events in future.  
   
* Social media: we promoted the event via several social media channels (facebook, twitter, livestream). Is there a particular aspect of social media we should focus on for future events?
 
* We collected comments on suggested improve for future events. These are collected as free text. It would be interesting to find out if there were any particular patterns in the responses of customers that would help us focus our efforts to improve?

* Finally, we are interested in the demographics of our members, and how this is split by location in Scotland. We’d also be interested in getting a map representation of our membership data split up by demographic. 


### Challenges

* As this is real data, there are some challenges to bear in mind, and the data will need cleaned and narrowed down appropriately.
Some of the datasets have multiple sheets, so make sure to check that all of the data is being read in.

* Some of the variables might need appropriately pivoted to get them in long format, as the website form separated different categorical responses to the same question into separate variables.

* For the final brief question, you’ll need to do some detective work to find the locations of the clubs (longitude and latitude).

### Audience
* For this project, please consider the audience to be a general audience who are not familiar with the project.
